# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1432, 538)
        self.prev_btn_1 = QtWidgets.QPushButton(Form)
        self.prev_btn_1.setGeometry(QtCore.QRect(30, 150, 88, 34))
        self.prev_btn_1.setObjectName("prev_btn_1")
        self.next_btn_1 = QtWidgets.QPushButton(Form)
        self.next_btn_1.setGeometry(QtCore.QRect(130, 150, 88, 34))
        self.next_btn_1.setObjectName("next_btn_1")
        self.prev_btn_2 = QtWidgets.QPushButton(Form)
        self.prev_btn_2.setGeometry(QtCore.QRect(30, 400, 88, 34))
        self.prev_btn_2.setObjectName("prev_btn_2")
        self.next_btn_3 = QtWidgets.QPushButton(Form)
        self.next_btn_3.setGeometry(QtCore.QRect(130, 400, 88, 34))
        self.next_btn_3.setObjectName("next_btn_3")
        self.enter_btn_2 = QtWidgets.QPushButton(Form)
        self.enter_btn_2.setGeometry(QtCore.QRect(130, 350, 88, 34))
        self.enter_btn_2.setObjectName("enter_btn_2")
        self.enter_btn_1 = QtWidgets.QPushButton(Form)
        self.enter_btn_1.setGeometry(QtCore.QRect(130, 100, 88, 34))
        self.enter_btn_1.setObjectName("enter_btn_1")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(240, 20, 1161, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_lab_1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_lab_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_lab_1.setObjectName("gridLayout_lab_1")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(240, 270, 1161, 201))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_img_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_img_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_img_2.setObjectName("gridLayout_img_2")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(240, 60, 1161, 201))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_img_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_img_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_img_1.setObjectName("gridLayout_img_1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 490, 1161, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_lab_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_lab_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_lab_2.setObjectName("gridLayout_lab_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 211, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 310, 211, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(90, 470, 88, 34))
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.prev_btn_1.setText(_translate("Form", "PushButton"))
        self.next_btn_1.setText(_translate("Form", "PushButton"))
        self.prev_btn_2.setText(_translate("Form", "PushButton"))
        self.next_btn_3.setText(_translate("Form", "PushButton"))
        self.enter_btn_2.setText(_translate("Form", "PushButton"))
        self.enter_btn_1.setText(_translate("Form", "PushButton"))
        self.exit_btn.setText(_translate("Form", "PushButton"))
